apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: quarked-jvm
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/target: "10"
            sidecar.istio.io/inject: "false"
        spec:
          container:
            image: docker.io/geoand/quarked-jvm:0.1
            resources:
              requests:
                memory: "150Mi"
                cpu: "500m"
              limits:
                memory: "150Mi"
                cpu: "500m"
            livenessProbe:
              initialDelaySeconds: 1
              successThreshold: 1
              periodSeconds: 1
              httpGet:
                path: /health/live
            readinessProbe:
              httpGet:
                path: /health/ready