apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: quarked
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/target: "10"
        spec:
          container:
            image: docker.io/geoand/quarked:0.1
            resources:
              requests: 
                memory: "50Mi" 
                cpu: "75m" 
              limits:
                memory: "150Mi"
                cpu: "150m"
            livenessProbe:
              initialDelaySeconds: 1
              httpGet:
                path: /health/live
            readinessProbe:
              initialDelaySeconds: 1
              httpGet:
                path: /health/ready