apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: booted
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/rhdevelopers/booted:0.0.1
            resources:
              requests: 
                memory: "150Mi" 
                cpu: "500m" 
              limits:
                memory: "150Mi"
                cpu: "500m" 
            livenessProbe:
              httpGet:
                path: /healthz
            readinessProbe:
              httpGet:
                path: /healthz