apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: booted
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/target: "10"
        spec:
          container:
            image: docker.io/geoand/booted:0.1
            resources:
              requests: 
                memory: "150Mi"
                cpu: "500m"
              limits:
                memory: "400Mi"
                cpu: "500m"
            livenessProbe:
              initialDelaySeconds: 1
              httpGet:
                path: /actuator/health
            readinessProbe:
              initialDelaySeconds: 1
              httpGet:
                path: /actuator/health