apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: quarkusapicrud
  name: quarkusapicrud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkusapicrud
  template:
    metadata:
      labels:
        app: quarkusapicrud
    spec:
      containers:
      - name: quarkusapicrud
        image: dev.local/rhdevelopers/quarkusapicrud:0.0.1
        ports:
          - containerPort: 8080
        resources:
          requests: 
            memory: "50Mi" 
            cpu: "200m" 
          limits:
            memory: "50Mi"
            cpu: "200m" 
        livenessProbe:
          httpGet:
              port: 8080
              path: /fruits
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 2          
        readinessProbe:
          httpGet:
            path: /fruits/healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 3

