apiVersion: v1
kind: Service
metadata:
  name: quarkusapicrud
  labels:
    app: quarkusapicrud    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: quarkusapicrud
  type: LoadBalancer