apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: quarked
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/rhdevelopers/quarked:0.0.1
            resources:
              requests: 
                memory: "50Mi" 
                cpu: "100m" 
              limits:
                memory: "50Mi"
                cpu: "100m" 
            livenessProbe:
              httpGet:
                path: /healthz
            readinessProbe:
              httpGet:
                path: /healthz