apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: csharp
  name: csharp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csharp
  template:
    metadata:
      labels:
        app: csharp
    spec:
      containers:
      - name: csharp
        image: quay.io/burrsutter/csharp:1.0.0     
        ports:
          - containerPort: 8080
        resources:
          requests: 
            memory: "130Mi" 
            cpu: "500m" 
          limits:
            memory: "130Mi"
            cpu: "750m" 
        livenessProbe:
          httpGet:
              port: 8080
              path: /
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 2          
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3

