apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: apicrud
  name: apicrud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicrud
  template:
    metadata:
      labels:
        app: apicrud
    spec:
      containers:
      - name: apicrud
        image: dev.local/rhdevelopers/apicrud:0.0.1
        ports:
          - containerPort: 8080
        resources:
          requests: 
            memory: "300Mi" 
            cpu: "250m" # 1/4 core
          limits:
            memory: "300Mi"
            cpu: "1000m" # 1 core
        livenessProbe:
          httpGet:
              port: 8080
              path: /fruits
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 2          
        readinessProbe:
          httpGet:
            path: /fruits/healthz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 3

