apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: gonow
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/rhdevelopers/gonow:0.0.1
            resources:
              requests: 
                memory: "10Mi" 
                cpu: "75m" 
              limits:
                memory: "10Mi"
                cpu: "75m" 
            livenessProbe:
              httpGet:
                path: /healthz
            readinessProbe:
              httpGet:
                path: /healthz