apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: noded
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          annotations:
            autoscaling.knative.dev/target: "10"
        spec:
          container:
            image: docker.io/geoand/noded:0.1
            resources:
              requests: 
                memory: "50Mi"
                cpu: "75m" 
              limits:
                memory: "100Mi"
                cpu: "75m" 
            livenessProbe:
              initialDelaySeconds: 0
              successThreshold: 1
              periodSeconds: 1
              httpGet:
                path: /healthz
            readinessProbe:
              initialDelaySeconds: 0
              successThreshold: 1
              periodSeconds: 1
              httpGet:
                path: /healthz